// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_frame`, `with_player`

Future<void> init() => RustLib.instance.api.crateApiInit();

Future<void> load({required String url}) =>
    RustLib.instance.api.crateApiLoad(url: url);

Future<void> play() => RustLib.instance.api.crateApiPlay();

Future<void> pause() => RustLib.instance.api.crateApiPause();

Future<void> stop() => RustLib.instance.api.crateApiStop();

Future<void> seek({required int positionMs}) =>
    RustLib.instance.api.crateApiSeek(positionMs: positionMs);

Future<void> setVolume({required double volume}) =>
    RustLib.instance.api.crateApiSetVolume(volume: volume);

Future<void> setPlaybackRate({required double rate}) =>
    RustLib.instance.api.crateApiSetPlaybackRate(rate: rate);

Future<int> positionMs() => RustLib.instance.api.crateApiPositionMs();

Future<int> durationMs() => RustLib.instance.api.crateApiDurationMs();

Future<int> bufferedPositionMs() =>
    RustLib.instance.api.crateApiBufferedPositionMs();

Future<VideoFrame?> tryPullFrame() =>
    RustLib.instance.api.crateApiTryPullFrame();

class VideoFrame {
  final int width;
  final int height;
  final int stride;
  final Uint8List data;

  const VideoFrame({
    required this.width,
    required this.height,
    required this.stride,
    required this.data,
  });

  @override
  int get hashCode =>
      width.hashCode ^ height.hashCode ^ stride.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoFrame &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          stride == other.stride &&
          data == other.data;
}
